// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9zUgZhQtN51zQPP3oYBKgs-KLonj3NcM',
    appId: '1:70223536860:web:7c0db37a034cdee2768a19',
    messagingSenderId: '70223536860',
    projectId: 'e-commerce-87fc8',
    authDomain: 'e-commerce-87fc8.firebaseapp.com',
    storageBucket: 'e-commerce-87fc8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlFsJ9Ww9YnOQ_OGv9C_ksFADxwicOCrM',
    appId: '1:70223536860:android:c5fb38aec162a51b768a19',
    messagingSenderId: '70223536860',
    projectId: 'e-commerce-87fc8',
    storageBucket: 'e-commerce-87fc8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO_ka7VviYGNt5KGGNEHgUbIcotAc31kE',
    appId: '1:70223536860:ios:c3eb67f7d37b1032768a19',
    messagingSenderId: '70223536860',
    projectId: 'e-commerce-87fc8',
    storageBucket: 'e-commerce-87fc8.appspot.com',
    iosClientId: '70223536860-ke8ha6qcbnj1tci4p95v5uaachu7jibm.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCO_ka7VviYGNt5KGGNEHgUbIcotAc31kE',
    appId: '1:70223536860:ios:6a8b3c5a47d7f0e8768a19',
    messagingSenderId: '70223536860',
    projectId: 'e-commerce-87fc8',
    storageBucket: 'e-commerce-87fc8.appspot.com',
    iosClientId: '70223536860-bsl385v0bgd52cm6jpcn2hckr5ktl9ss.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce.RunnerTests',
  );
}
